#!/usr/bin/env bash
# Install the Meet Live Assist bridge server as a launchd agent on THIS Mac.
# Resolves every machine-specific path itself (node binary, repo location, Homebrew prefix),
# so the same script works on Apple Silicon and Intel, with any node manager.
#
#   ./server/install-server.sh                          # install + start
#   TRANSCRIPTS_DIR=~/mla PORT=8849 ./server/install-server.sh
#   MLA_DRY_RUN=1 ./server/install-server.sh             # print the plan + plist, change nothing
#
# Idempotent: re-running regenerates the plist and restarts the service.
set -euo pipefail

LABEL=com.mla.meet-transcript-server
REPO_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SERVER_JS="$REPO_DIR/server/transcript-server.js"
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"
LOG_FILE="$HOME/Library/Logs/meet-live-assist-server.log"
PORT=${PORT:-8848}
# Not under the repo by default: transcripts are meeting PII and must not risk being committed.
TRANSCRIPTS_DIR=${TRANSCRIPTS_DIR:-$HOME/meet-live-assist/transcripts}
DRY=${MLA_DRY_RUN:-0}

die() { printf '❌ %s\n' "$1" >&2; exit 1; }

[ -f "$SERVER_JS" ] || die "not found: $SERVER_JS (run this from a full clone of the repo)"
command -v node >/dev/null || die "node not found — install Node 20+ (brew install node, or fnm/nvm)"

# process.execPath, not `which node`: fnm/nvm expose a per-shell shim that dies with the shell,
# and launchd needs a path that still exists at login.
NODE_BIN=$(node -e 'process.stdout.write(process.execPath)')
NODE_MAJOR=$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))')
[ "$NODE_MAJOR" -ge 20 ] || die "node $NODE_MAJOR is too old — need 20+"

# Optional deps. The server starts without them; TTS-into-call and local STT degrade.
FFMPEG_BIN=$(command -v ffmpeg || true)
WHISPER_BIN=$(command -v whisper-cli || true)

node --check "$SERVER_JS" || die "$SERVER_JS failed a syntax check"

xml_entry() { printf '    <key>%s</key>\n    <string>%s</string>\n' "$1" "$2"; }

build_plist() {
  cat <<PLIST_HEAD
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by server/install-server.sh — re-run it instead of hand-editing. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>

  <key>ProgramArguments</key>
  <array>
    <string>$NODE_BIN</string>
    <string>$SERVER_JS</string>
  </array>

  <key>EnvironmentVariables</key>
  <dict>
PLIST_HEAD
  xml_entry PORT "$PORT"
  xml_entry TRANSCRIPTS_DIR "$TRANSCRIPTS_DIR"
  [ -n "$FFMPEG_BIN" ] && xml_entry FFMPEG "$FFMPEG_BIN"
  [ -n "$WHISPER_BIN" ] && xml_entry WHISPER_CLI "$WHISPER_BIN"
  cat <<PLIST_TAIL
  </dict>

  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>$LOG_FILE</string>
  <key>StandardErrorPath</key>
  <string>$LOG_FILE</string>
</dict>
</plist>
PLIST_TAIL
}

printf 'node          %s (v%s)\n' "$NODE_BIN" "$NODE_MAJOR"
printf 'server        %s\n' "$SERVER_JS"
printf 'transcripts   %s\n' "$TRANSCRIPTS_DIR"
printf 'port          %s\n' "$PORT"
printf 'log           %s\n' "$LOG_FILE"
printf 'ffmpeg        %s\n' "${FFMPEG_BIN:-— missing (TTS into the call disabled)}"
printf 'whisper-cli   %s\n' "${WHISPER_BIN:-— missing (local STT disabled)}"

if [ "$DRY" = 1 ]; then
  printf '\n--- would write %s ---\n' "$PLIST"
  build_plist
  printf '\n(dry run — nothing installed)\n'
  exit 0
fi

mkdir -p "$TRANSCRIPTS_DIR" "$HOME/Library/LaunchAgents" "$(dirname "$LOG_FILE")"
build_plist > "$PLIST"

launchctl unload -w "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"

for _ in $(seq 1 20); do
  if curl -fsS "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then
    printf '\n✅ server up on 127.0.0.1:%s\n' "$PORT"
    printf '   token (paste into the extension Options): %s\n' "$(cat "$TRANSCRIPTS_DIR/.mla-token")"
    printf '   restart: launchctl kickstart -k gui/$UID/%s\n' "$LABEL"
    printf '   stop:    launchctl unload -w %s\n' "$PLIST"
    exit 0
  fi
  sleep 0.5
done

die "server did not answer /health within 10s — check $LOG_FILE"
